### PR TITLE
New PX build with volume options

### PR DESCRIPTION
**Pull request by sensri108**

### CODE REVIEW

**Comment by deniseschannon** [comment]
@senpx If you want to add in a new field in a template, you'll need to make sure to create a new template (new folder) with the changes. Typically, to merge stuff in, we prefer a single commit which is the copy of the previous folder/template. Then a second commit with the changes on the template.

**Comment by sensri108** [comment]
Hi Denise

 

Sorry for the delay, I have pushed my commits as you guided. Can you please review it and approve the same? 

 

Thanks in advance. 

 

Sen S

**Comment by deniseschannon** [comment]
@senpx did you push the commits to your branch cause i don't see any changes.

**Comment by rawmind0** [comment]
Duplicated https://github.com/rancher/rancher-catalog/pull/995

**Pull request closed without merging**
