### PR TITLE
Route53 v0.6.0

### PR DESCRIPTION
**Pull request by janeczku**
Validated in qa branch

https://github.com/rancher/rancher/issues/5273
https://github.com/rancher/rancher/issues/4066
https://github.com/rancher/rancher/issues/3972

### CODE REVIEW

**Comment by deniseschannon** [comment]
@janeczku can you update the route53 catalog in the infra-template as well?

**Comment by janeczku** [comment]
@deniseschannon infra-template is already updated https://github.com/rancher/rancher-catalog/tree/master/infra-templates/route53/8

**Comment by deniseschannon** [comment]
@janeczku Small nitpick. 

Can you update infra-templates so that the variable for `HEALTH_CHECK_INTERVAL` is consistent with what we're updating here? In infra-templates, it's `HEALTH_CHECK`?

**Comment by janeczku** [comment]
@deniseschannon I updated this PR to have the same variable name as the infra-template template.

**Pull request merged**
