### PR TITLE
Add PointHQ DNS template

### PR DESCRIPTION
**Pull request by haswalt**

### CODE REVIEW

**Comment by alena1108** [comment]
@haswalt could you change the external dns version to v0.2.0? From now on, all new releases including new features, will come with incremented middle digits, and the last digit will be incremented for bug fixes releases.

**Comment by haswalt** [comment]
@alena1108 done :)

**Comment by alena1108** [comment]
@haswalt @vincent99 @cloudnautique would .png logo be ok? I see that in all our other templates we use .svg format for images.

**Comment by haswalt** [comment]
@alena1108 PointHQ don't have / won't provide an SVG version of the logo and i'm not a good enough designer to convert the PNG to svg properly. It shows up on the catalog list page ok, however is slightly blurred due tot he scaling on the detail page.

**Comment by alena1108** [comment]
@lvuch @vincent99 ^^ would need your help again with making .svg logo for PointHQ dns

**Comment by alena1108** [comment]
LGTM. Although not desirable, we can merge with .png logo and change it later to .svg. @cloudnautique @vincent99

**Comment by vincent99** [comment]
Template looks fine to me, I'd like to have a icon with the header like the others but we can add that from @lvuch after merging.

**Pull request merged**
