### PR TITLE
Adding Portworx v1.7.1.1 entry

### PR DESCRIPTION
**Pull request by zoxpx**
* adding Portworx v1.7.1.1 (Nov 6 2018)

### CODE REVIEW

**Comment by deniseschannon** [comment]
@zoxpx We have started putting in development work in the `v1.6-development` branch, which will not be released for awhile. Could you rebase this so that it is on top of the `v1.6-release` branch so it could go out immediately? If you make your future PRs to that branch, I can always merge it without waiting for Rancher development.

Just a reminder, this means that the updates are available to anyone with catalogs using internet, but our anyone with airgapped relying on the cached catalog won't receive these until a new release of Rancher is released.

**Comment by zoxpx** [comment]
Hello @deniseschannon -- I have rebased this PR's merge-branch as you requested.

**Comment by deniseschannon** [comment]
Thanks @zoxpx

**Comment by zoxpx** [comment]
Thank you very much Denise -- deleting the merge-branch

**Pull request merged**
