### PR TITLE
Add Cloudflare DNS catalog entry

### PR DESCRIPTION
**Pull request by janeczku**
Version is set to v0.1.9 which is the next release. This still needs a logo.

### CODE REVIEW

**Comment by patryk** [comment]
s/Cloudflare/CloudFlare/

**Comment by janeczku** [comment]
@patryk whats that mean? :smile:

**Comment by patryk** [comment]
Correct brand name, should be "CloudFlare" (with capital C and F), not Cloudflare. https://www.cloudflare.com/spelling/

Just cosmetic change :)

**Comment by janeczku** [comment]
@patryk Ah right, thats what you "sed" ! :laughing: I will correct the spelling. Dzieki za uwage!

**Comment by alena1108** [comment]
LGTM. I'll update the PR once external-dns v0.1.9 is released, so we can test this template using the new image.

**Comment by janeczku** [comment]
@alena1108 That's awesome :smile:

**Comment by alena1108** [comment]
@janeczku the image is uploaded to the docker hub; could you give one more test to this catalog item? It it passes, we are going to merge it.

**Comment by janeczku** [comment]
@alena1108 cool, i will test and report back to you

**Comment by janeczku** [comment]
@alena1108 I tested the catalog entry for CloudFlare with the current Rancher release. No issues. CloudFlare still needs a logo image though (the catalogIcon-cloudflare.svg in the PR is just a placeholder)!

**Comment by alena1108** [comment]
@janeczku sure, @vincent99 @lvuch ^^ need your help with logo :)

**Comment by alena1108** [comment]
@janeczku here is the logo:

https://www.dropbox.com/s/r64xx7f4hcqm3gv/catalog_dns_cloudflare_cloudflare.svg

once its in, we can merge this PR :)

**Comment by janeczku** [comment]
@alena1108 done! :sparkles: :tada:  :grinning:

**Comment by alena1108** [comment]
@cloudnautique could you merge it? I don't have "super-duper" permissions in this repo :)

**Pull request merged**
