### PR TITLE
Enabling VXLAN catalog for kubernetes

### PR DESCRIPTION
**Pull request by leodotcloud**
https://github.com/rancher/rancher/issues/7938

### CODE REVIEW

**Comment by sangeethah** [comment]
@leodotcloud , k8s with vxlan using - rancher/net:v0.9.3  works fine. Related issue was verified and close by hussain using latest master builds -   https://github.com/rancher/rancher/issues/6817

**Comment by deniseschannon** [comment]
Did we test with rancher/net:v0.9.3 or v0.9.2? Currently, the template has v0.9.2.

**Comment by deniseschannon** [comment]
I have an issue with this. As soon as we merge this into master, it will show up for anyone running any version of k8s.

**Comment by leodotcloud** [comment]
@deniseschannon we had a discussion on slack and we wanted to enable rancher_minimum_version on all catalog items before merging to master.

**Comment by sangeethah** [comment]
This was specifically tested with rancher/net:v0.9.3 (present in branch v1.5.0-dev).  with rancher/net:v0.9.2 , we have issues with K8s using vxlan.

**Pull request merged**
