### PR TITLE
Expose `linkMTUOverhead` via `$LINK_MTU_OVERHEAD` config var in `ipsec`, `vxlan`

### PR DESCRIPTION
**Pull request by rysiekpl**
Fix for https://github.com/rancher/rancher/issues/11438

### CODE REVIEW

**Comment by rysiekpl** [comment]
Help in properly formatting the changelog message would be appreciated. Also, this should probably get pulled into other branches too.

**Comment by deniseschannon** [comment]
We would only accept this change in templates to any template that is not already released. 

The only applicable folder this should be in would be folder 16 for ipsec (new for the upcoming release) and creating a new folder for vxlan. 

vxlan should have 2 commits, 1 commit for a new folder (copying folder 13 to folder 14) and then another commit for the changes that you've introduced. 

As for the changelog, you can add in the readme for that specific folder ```* Added ability to change the `linkMTUOverhead` setting

**Comment by rysiekpl** [comment]
@deniseschannon affirmative. Will reformat. Thanks!

**Comment by deniseschannon** [comment]
@rysiekpl I spoke with @leodotcloud. Before you make any changes, he has some comments on configuring this field. He'll put on the original issue.

**Comment by alena1108** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches

**Pull request closed without merging**
