### PR TITLE
Add Portworx 1.3.0 to 1.4.0 releases

### PR DESCRIPTION
**Pull request by zoxpx**
add version 1.4.0.0-oci  ( Tue Jul  3 16:52:33 2018 -0700 )
add version 1.3.6.0-oci  ( Mon Jul  2 16:00:57 2018 -0700 )
add version 1.3.4.0-oci  ( Fri Jun 22 13:18:45 2018 -0700 )
add version 1.3.3.0-oci  ( Thu May 31 22:50:44 2018 -0700 )
add version 1.3.2.0-oci  ( Tue May 29 13:41:45 2018 -0700 )
add version 1.3.1.4-oci  ( Tue May 29 13:41:45 2018 -0700 )
add version 1.3.1.2-oci  ( Mon Apr 30 14:28:18 2018 -0700 )
add version 1.3.1.1-oci  ( Mon Apr 16 16:43:01 2018 -0700 )
add version 1.3.0-oci.2  ( Fri Apr 13 13:35:57 2018 -0700 )
add version 1.3.0-oci    ( Mon Apr  9 17:34:28 2018 -0700 )

### CODE REVIEW

**Comment by zoxpx** [comment]
Thanks very much @deniseschannon

**Comment by zoxpx** [comment]
@deniseschannon -- two quick questions if you don't mind.
When can we expect these changes to make it into the Rancher-16's "Rancher Certified Library"?
Will they appear for everyone running Rancher-16 (i.e. "pull" from Github), or will it be visible only to latest Rancher-installs?

**Comment by deniseschannon** [comment]
We're planning on releasing v1.6.19 in the next couple of days, with that, we'll package up what is in 1v1.6-development1 and push to the `v1.6-release` branch. 

These will be available to everyone who has internet access and their catalogs can be refreshed automatically. If they don't have access to the internet, it will only be packaged in new installs going forward.

**Comment by zoxpx** [comment]
Thank you again @deniseschannon

**Pull request merged**
