### PR TITLE
Portworx catchup 11

### PR DESCRIPTION
**Pull request by zoxpx**
* adding Portworx v1.7.4 entry (2019-01-07)
* adding Portworx v1.7.5 entry (2019-01-15)

### CODE REVIEW

**Comment by zoxpx** [comment]
NOTE, PR uses `rancher:v1.6-release` baseline, to be consistent w/ previous PR's instructions.

**Comment by deniseschannon** [comment]
@zoxpx Did you want to use one of these versions as the default? If so, you need to update the `config.yml`.

**Comment by zoxpx** [comment]
@deniseschannon -- thanks for the heads-up, but this PR should be fine as it is.
The 1.7.4 and 1.7.5 from the PR are our patch-releases, while we have our latest version v2.0.1 listed in `config.yml`.

**Comment by deniseschannon** [comment]
:+1: Thanks @zoxpx, I just wanted to double check.

**Comment by zoxpx** [comment]
Thanks Denise  -- much appreciated.

**Pull request merged**
