### PR TITLE
Portworx catalog templates are updated. 

### PR DESCRIPTION
**Pull request by sensri108**
Portworx catalog templates are updated. We will keep updating more content and templates going forward. Currently, we are using the mostly private catalog for all our internal testing. But we want to keep this structure and adding new template going forward.

### CODE REVIEW

**Comment by deniseschannon** [comment]
@senpx There's a conflict in the config.yml which makes it impossible to merge. Can you fix that?

**Comment by sensri108** [comment]
@deniseschannon can we have quick webex call to clear this pull request please? . Its really getting delayed. and new customers are using wrong templates.

**Comment by deniseschannon** [comment]
@senpx if you can get the PR into a clean state where it can be merged, that's all you would need to do at this point.

**Comment by sensri108** [comment]
I am not sure which branch will be published(public catalog) to the customer.  I believe 'v1.6-development' is the correct branch. and also what you mean clean state? can we have a quick call to understand the same?  Please let me know for further details.

**Comment by deniseschannon** [comment]
To give it to the public, it needs to be `v1.6-release`.

**Comment by sensri108** [comment]
I have changed it back to 'v1.6-release'.

**Comment by sensri108** [comment]
is there any action item pending from my side?

**Comment by deniseschannon** [comment]
@senpx Yes, you need to rebase your branch so that there are no merge conflicts.

**Pull request closed without merging**
