### PR TITLE
Portworx versions catchup #3

### PR DESCRIPTION
**Pull request by zoxpx**
Adding the following portworx versions:
* 19d328c Adding Portworx v1.5.0.0 entry (Aug 22 2018)
* b81474e Adding Portworx v1.4.2.2 entry (Aug 10 2018)
* 7beb33a Adding Portworx v1.4.2.1 entry (Aug 1 2018)

### CODE REVIEW

**Comment by deniseschannon** [comment]
@zoxpx As we have some items in this branch that need to be validated before it can get released, can you start off of the `v1.6-release` branch and then make tehse changes so that I can directly release this?

**Comment by zoxpx** [comment]
As requested, created a new https://github.com/rancher/rancher-catalog/pull/1173 with the same changes.  Should we close this pull-request?

**Comment by zoxpx** [comment]
Note, the identical https://github.com/rancher/rancher-catalog/pull/1173 got merged directly into `v1.6-release` -- should we close this pull-request?

**Comment by zoxpx** [comment]
thank you very much @deniseschannon

**Comment by deniseschannon** [comment]
@zoxpx i've pulled in the `v1.6-release` commits into `v1.6-development` branch so that it's up to date!

**Comment by zoxpx** [comment]
Thanks for letting us know  :)

**Pull request closed without merging**
