### PR TITLE
addon-starter healthcheck

### PR DESCRIPTION
**Pull request by joshwget**
Depends on https://github.com/rancher/kubernetes-package/pull/88

https://github.com/rancher/rancher/issues/9577

### CODE REVIEW

**Comment by alena1108** [comment]
@joshwget could you increase init/reinit timeout to 2 mins just in case the addons take a while to deploy?

**Comment by alena1108** [comment]
@deniseschannon lets hold on merging this PR. QA already started testing upgrade using rancher7 template. We can merge it later in case more bugs are discovered and another round of upgrade testing is needed.

**Comment by joshwget** [comment]
@alena1108 I adjusted the timeouts to 3 minutes since this actually takes longer than I realized. Let me know if you think that's too long.

**Comment by deniseschannon** [comment]
@joshwget Can you rebase and create a new folder for this addition?

**Comment by deniseschannon** [comment]
Closed in favor of https://github.com/rancher/rancher-catalog/pull/833

**Pull request closed without merging**
