### PR TITLE
Added new portworx catalog templates(1.2.14 & 1.3) and updated edge version

### PR DESCRIPTION
**Pull request by sensri108**
Added new portworx catalog templates(1.2.14 & 1.3) and updated edge version. This is an urgent request, customer waiting for the same. thanks in advance.

### CODE REVIEW

**Comment by deniseschannon** [comment]
Can you please update these and put them into the `v1.6-development` branch? `master` branch is used for older releases. The latest stuff goes into `v1.6-development` before merging into `v1.6-release`. 

Ideally, can you squash the commits as well? It'd be cleaner if the first commit for the new versions was just a copy of the folder and then another commit of the changes from the last template. It makes it easier to review and make sure the appropriate places for version/image changes are updated.

**Comment by sensri108** [comment]
as you mentioned,  i have updated the branch to v1.6-development. Please review the same and merge it asap. its urgent and customer waiting for the same.

**Comment by deniseschannon** [comment]
if you need it for a customer, i need you to actually rebase it to `v1.6-release` and clean up all commits. currently, changing the branch doesn't allow it to be merge-able.

**Comment by sensri108** [comment]
Yes, Please do necessary consolidation and clean up. Please let me know, If you want me to take care anything. Awaiting for your update asap. thanks

**Comment by deniseschannon** [comment]
You need to rebase your branch and make the changes to your PR as I requested about cleaning up the commits.

**Comment by sensri108** [comment]
Created another PR(#1078) to v1.6-development as recommended and canceling this PR.

**Pull request closed without merging**
