### PR TITLE
Map /var/log/containers from kubelet to host to enable log aggregation

### PR DESCRIPTION
**Pull request by ryanwalls**
Fixes https://github.com/rancher/rancher/issues/7688

### CODE REVIEW

**Comment by alena1108** [comment]
@ryanwalls does it require any changes in [kubernetes-package](https://github.com/rancher/kubernetes-package) repo (entry.sh)? Or template fix is sufficient enough? If the latter, could you recreate your PR against v1.5.0-dev branch, folder number 19.

**Comment by ryanwalls** [comment]
@alena1108 I did change the kubernetes-package repo.  See https://github.com/3DSIM/kubernetes-package/commit/02602826a5f6eea9d5caca664c19d5e630195045.  I don't know if the change was necessary.

**Comment by alena1108** [comment]
@ryanwalls given that other user submitted similar PR w/o changing kubernetes-package/image startup scripts, looks like the template fix might be sufficient enough: https://github.com/rancher/rancher-catalog/pull/450

**Comment by alena1108** [comment]
Closing in favor of PR opened against 1.5 dev branch https://github.com/rancher/rancher-catalog/pull/484

**Pull request closed without merging**
