### PR TITLE
Updated Portworx Rancher catalog

### PR DESCRIPTION
**Pull request by sensri108**

### CODE REVIEW

**Comment by sensri108** [comment]
Resubmitting new pull request as per guidance. Portworx catalog templates are updated. We will keep updating more content and templates going forward. Currently, we are using the mostly private catalog for all our internal testing. But we want to keep this structure and adding new template going forward. Please approve and merge it asap. thanks in advance.

**Comment by deniseschannon** [comment]
@senpx Do you need to make the changes in the files for folder 0? Those changes could change/affect how existing users have their templates changed. I would remove those changes and just introduce the new templates. 

If you want those templates to be removed from being used by any user, you can update the `minimum_rancher_version` and `maxiumum_rancher_version`  to be the same in the `catalog` section of the rancher-compose.yml.

**Comment by sensri108** [comment]
this is the correct format. yes, even 0 folder needs to be updated. We want all the customers use this. Basically, that will reduce our support calls. thanks in advance.

**Comment by deniseschannon** [comment]
@senpx Altering the templates in folder 0 will not fix any existing deployments and could cause additional support calls as Rancher *never* introduce changes to existing released templates  changes. I would *not* merge this PR inwith those changes. 

 If you want them to upgrade to a new version or fix that version, then you should make the template obsolete by adding the `minimum_rancher_version` and `maximum_rancher_version` and introduce another template.

**Comment by sensri108** [comment]
I do understand that and we spoke to Nick and William over the call about this changes. That’s why I am asking for the call to fix everything and close it. It’s keep dragging all this way still. Either I request your time for a call and fix this or I have to escalate this with no further delays. We do understand, this changes will impact in positive way only and reduce our support call. Please let me know, if you need further clarifications. Thanks in advance.

**Comment by sensri108** [comment]
Now it looks good. thanks for your understanding and help.

**Pull request merged**
