### PR TITLE
Updating to latest nDVP plugin version

### PR DESCRIPTION
**Pull request by rippy**
Updating the NetApp Docker Volume plugin catalog item entries from nDVP version 1.3.3 to nDVP version 17.07

### CODE REVIEW

**Comment by deniseschannon** [comment]
Are you okay with having this available across all versions of Rancher?

**Comment by rippy** [comment]
Yes

**Comment by deniseschannon** [comment]
Can you rebase this PR again? Sorry about that, we were in the middle of a release, so couldn't merge it immediately.

**Comment by rippy** [comment]
Submitted a new PR with the change you wanted, closing this one.

New one here:
https://github.com/rancher/rancher-catalog/pull/834

**Pull request closed without merging**
