### PR TITLE
Rename k8s docker-compose.yml to docker-compose.yml.tpl

### PR DESCRIPTION
**Pull request by joshwget**
@cloudnautique This should make CI skip validation on this file.

Can't be merged until the UI can recognize this filename (@vincent99).

cc @LLParse @deniseschannon

### CODE REVIEW

**Comment by LLParse** [comment]
LGTM, presuming UI can understand it

**Comment by vincent99** [comment]
UI will prefer `.yml.tpl` now if present.

**Comment by deniseschannon** [comment]
@joshwget can you rebase?

**Comment by joshwget** [comment]
@deniseschannon Done

**Pull request merged**
