### PR TITLE
add a dnsimple service entry

### PR DESCRIPTION
**Pull request by nlf**
still needs an icon and i'm sure i probably didn't get the versions right..

### CODE REVIEW

**Comment by vincent99** [comment]
@lvuch Did you make an icon for this?

**Comment by alena1108** [comment]
@nlf dnsimple support was added in external dns v0.1.8; so the version has to be fixed. Lets set it to the latest version - v0.1.9 (and image version as well)

**Comment by nlf** [comment]
Done. Sorry for the three commits, did it via mobile

**Comment by alena1108** [comment]
@nlf np, we can squash it later, after we get the logo in. Have you made an icon for the service, or do you want us to add it in?

**Comment by nlf** [comment]
I believe @vincent99 had requested @lvuch create an icon. Said something about wanting to keep a consistent feel. So whenever that's ready, or if you folks have a different icon you'd like to use, please do go ahead and add it in.

**Comment by vincent99** [comment]
@nlf GitHub won't take an embedded svg, but http://vtf.me/catalog_dns_dnssimple.svg

**Comment by nlf** [comment]
added the icon

**Comment by alena1108** [comment]
LGTM

**Comment by ibuildthecloud** [comment]
@nlf Can you squash so we can merge? Thanks

**Comment by nlf** [comment]
squashed and ready to go

**Pull request merged**
