### PR TITLE
configurable arpsync interval for network-manager

### PR DESCRIPTION
**Pull request by gitlawr**
Address issue: https://github.com/rancher/rancher/issues/15729

### CODE REVIEW

**Comment by alena1108** [comment]
@gitlawr we can't modify the existing templates as they've been released to the community. You'd have to create a new folder, and do the changes there.

**Comment by gitlawr** [comment]
I see, updated.

**Comment by leodotcloud** [comment]
@gitlawr Can you please take care of the following comments:
There needs to be two commits when making a new template version. First commit is with the copy of the contents of the previous version and the second commit with just the changes made. Otherwise, it's impossible to figure out what has changed.

**Comment by gitlawr** [comment]
@leodotcloud Thanks for your advice. I learned that in another pr, but forgot to update here. The commit is split now.

**Review by leodotcloud — APPROVED** [review]
LGTM

**Pull request merged**
