### PR TITLE
Change the registry address and namespace of Pod Infra Container Image

### PR DESCRIPTION
**Pull request by xiaoluhong**

### CODE REVIEW

**Comment by yasker** [comment]
Please don't install `jq` in the script. It's not a user-facing script, we can ask our guys to install jq beforehand.

**Comment by xiaoluhong** [comment]
@yasker It has been changed. Please review it. Thanks

**Comment by yasker** [comment]
@hongxiaolu Thinking about it, sync all the tags for a certain image is too much and unnecessary. We only need to sync the images we used in the release.

So I think we can modify the script to read from an `image-sync.yaml` file, which looks like this:
```
from: gcr.io/google_containers
to: rancher
images:
- pause-amd64:3.0
- k8s-dns-kube-dns-amd64:1.14.5
- k8s-dns-dnsmasq-nanny-amd64:1.14.5
- k8s-dns-sidecar-amd64:1.14.5
- cluster-proportional-autoscaler-amd64:1.0.0
```

Then the script will only sync the images in the list from `from` to `to`.

`image-sync.yaml` can be committed later in the repo as well to make sure we have the version on record.

**Comment by xiaoluhong** [comment]
@deniseschannon  New PR  https://github.com/rancher/rancher-catalog/pull/1071

**Pull request closed without merging**
