### PR TITLE
Portworx catchup 17

### PR DESCRIPTION
**Pull request by zoxpx**
* adding Portworx v2.0.3.3 entry
* adding Portworx v2.0.3.4 entry
* adding Portworx v2.1.0.0 entry

### CODE REVIEW

**Comment by zoxpx** [comment]
@deniseschannon -- the tests seem to be failing.
Is the error on our side, or is it with your test-infrastructure  (I saw `jq: error: Cannot iterate over null` and `curl: no URL specified!` in the log)

**Comment by deniseschannon** [comment]
@zoxpx nothing has changed on the tests for this repo in a very long time, but let me check with the infrastructure team.

**Comment by zoxpx** [comment]
Oh.. looks like the checks have passed  (perhaps a build-system's temporary glitch?)

**Comment by deniseschannon** [comment]
I asked our team to restart the drone build!

**Comment by zoxpx** [comment]
Thank you very much @deniseschannon

**Pull request merged**
