### PR TITLE
Latest Weave Scope release

### PR DESCRIPTION
**Pull request by errordeveloper**
Add new release of Weave Scope (_v0.12.0_).

### CODE REVIEW

**Comment by errordeveloper** [comment]
This is first time I'm bumping the version, so please let me know if I understood the process quite right.

**Comment by cloudnautique** [comment]
Just to confirm theres no data or anything that would get lost? Just new Docker images.

**Comment by errordeveloper** [comment]
Yep, just new images. Scope currently doesn't persist anything on disk.

**Comment by cloudnautique** [comment]
LGTM

**Pull request merged**
