### PR TITLE
Add spinnaker template.

### PR DESCRIPTION
**Pull request by johnrengelman**
Catalog entry for Netflix's Spinnaker project.

### CODE REVIEW

**Comment by cloudnautique** [comment]
Hello,

Could you open this PR against rancher/community-catalog please? We are going to be separating out the templates provided by Rancher and the community.

**Comment by cloudnautique** [comment]
@johnrengelman, This would be a really good addition to the rancher/community-catalog. It was launched as part of the v0.59.0 release.

**Comment by johnrengelman** [comment]
@cloudnautique - I've got that staged up but I need to test it again with the newer versions of Spinnaker to make sure that the config hasn't changed too dramatically. You can close this PR. I will try and get a new one submitted when I'm back from vacation.

**Comment by cloudnautique** [comment]
Sounds good. Thanks.

**Pull request closed without merging**
