### PR TITLE
[DO NOT MERGE] update kubernetes with etc-host-updater

### PR DESCRIPTION
**Pull request by wlan0**
@ibuildthecloud @alena1108 - This is a placeholder PR. It shows the template for integrating kube-api-server with the `etc-hosts-updater` service.

### CODE REVIEW

**Comment by alena1108** [comment]
Thank you @wlan0! 

As this PR will most likely be the one introducing k8s 1.3, we should make sure that:
- both k8s and kubectld images tags get updated to 1.3 rancher release of corresponding repos
- the template should have minimum rancher version 1.1
- the template should NOT be default (skip registering it in config.yml)

**Comment by alena1108** [comment]
rancher/rancher#4664
rancher/rancher#4384

**Comment by ibuildthecloud** [comment]
When updating templates it's nice if we do it in two commits.  The first commit copies the old version as is into a new folder.  The next commit makes the needed changes.  This way we get some type of diff.

**Comment by danisla** [comment]
@wlan0 what does the `etc-hosts-updater` service do?

**Comment by wlan0** [comment]
@danisla etc-hosts-updater maintains the hostname:ipaddress mappings of all the current kubernetes nodes. This is needed by the kube-api-server to resolve hostnames for operations such as - 
1. kubectl logs
2. kubectl attach
3. kubectl exec

**Comment by ibuildthecloud** [comment]
@danisla etc-hosts-updater is to work around issues in which the k8s nodes' hostname is not a properly resolvable DNS entry.  Basically working around https://github.com/kubernetes/kubernetes/issues/22063

**Pull request closed without merging**
