### PR TITLE
kubernetes master HA

### PR DESCRIPTION
**Pull request by imikushin**
Scale kubernetes api-server, controller-manager and scheduler to 2 instances when possible.

### CODE REVIEW

**Comment by imikushin** [comment]
rancher/rancher#5235

**Comment by LLParse** [comment]
What happens to on-cluster apiserver requests (via the kubernetes service) when `--apiserver-count=2` is set but only 1 host is in the environment?

**Comment by imikushin** [comment]
@LLParse that is a good question. 

Without this option (by default `--apiserver-count=1`) api-server instances compete for being the 1 and only kubernetes service endpoint. The following message appears in `kubernetes-N` container logs every few seconds:
```
W0509 03:57:30.444817       1 controller.go:386] Resetting endpoints for master service "kubernetes" to &{{ } {kubernetes  default /api/v1/namespaces/default/endpoints/kubernetes 8876dfd6-3417-11e7-a694-02ffb2eba332 58053 0 2017-05-08 17:55:33 +0000 UTC <nil> <nil> map[] map[] [] [] } [{[{10.42.23.236  <nil> <nil>}] [] [{https 6443 TCP}]}]}
```

With this option, however, the failed api-server instance endpoint still remains in the list of kubernetes service endpoints:
```
$ kubectl get ep
NAME         ENDPOINTS                              AGE
kubernetes   10.42.23.236:6443,10.42.231.200:6443   6h
```

If we initially have only two hosts with `orchestration=true`, and one of them fails, then we have a connectivity problem, because one of the endpoint IPs is unavailable. 

So, the recommendation is to have **more than 2 hosts** with `orchestration=true` label. This will minimize the impact by starting another api-server instance on a different host.

**Comment by imikushin** [comment]
Competition might not be a bad thing, though :) 

Because when that's the case the API is actually available, although maybe served from a different endpoint each time. The api-server logs are a bit swamped - that might be a downside.

**Comment by joshwget** [comment]
A few thoughts on this.

1. We should just set scale instead of using scale policy. Scale policy is going to be removed soon.
2. HA Kubernetes shouldn't be the default. We should change the `CONSTRAINT_TYPE` variable to `HA` and parameterize based on that.
3. I don't think the proxy fix is needed as part of this PR. We can create a separate PR for this later.

**Comment by LLParse** [comment]
Thanks @imikushin for the explanation. I was merely curious if there were ramifications for setting the count >1 when only 1 host is present. Otherwise, why not set it to `--apiserver-count=42` just to be safe, ya know?

I tend to agree we should parameterize scale. Configuration would be simpler. Etcd scale policy should probably be removed as well.

**Comment by imikushin** [comment]
If only one host is present initially (when we deploy k8s) all api-server requests go to the only api-server instance.

**Comment by LLParse** [comment]
Oh, so it sounds like the 1->2 transition will work correctly. Would there be lasting problems if we scaled 2->1? Does the 2nd endpoint get removed after some amount of time?

**Comment by imikushin** [comment]
I didn't notice the 2nd endpoint (failed) being removed, at least not in a few minutes.

**Comment by imikushin** [comment]
@joshwget mentioned scale policies are going away. 

If we warn in the README that there should be at least 2 hosts with `orchestration=true` when deploying in HA, then it's probably fine just to use scale=2 for api-server, scheduler and controller-manager. But it's probably not fine for etcd. 

Also, etcd operator should probably be used for etcd babysitting.

Thoughts?

**Comment by LLParse** [comment]
Scale policy is going away in the sense that it is being rewritten. The concept of scale policy is sound, but there are issues in the current implementation. The new scale policy impl would augment the global service impl, adding a scale limit.

I'm still afraid of the 2->1 transition causing problems. Consider a 1-node cluster. User needs more resources, so he adds a 2nd host with more RAM. Things stabilize, user then deletes the old host. Now there are 2 K8s endpoints, one of which is dead and will never be removed(?), so 50% of in-cluster API requests fail indefinitely until user manual intervenes. https://github.com/kubernetes/kubernetes/issues/22609

We are in agreement on etcd-operator. Here's the PR https://github.com/rancher/rancher-catalog/pull/650

**Pull request closed without merging**
