### PR TITLE
Elasticsearch v2.1.1 / Logstash v2.1.1 / Kibana v4.3.1 Rancher catalog templates

### PR DESCRIPTION
**Pull request by mgolly**
# Changes from elasticsearch v1.7.3 template
## docker-compose.yml

Use new rancher elasticsearch-conf v0.5.0 docker image.
Use new rancher kopf v0.5.0 docker image.
## rancher-compose.yml

Set template version to "2.1.1-rancher1"
## config.yml

Set default template version to use to "2.1.1-rancher1"
# Changes from Logstash v1.5.3 template
## docker-compose.yml

Use logstash:2.1.1-1 image from docker hub.
## rancher-compose.yml

Set template version to "2.1.1-1-rancher1"
Change default elasticsearch output config:
- "host" is now "hosts", is an array, and the array entries follow 'address:port'.
- "port" no longer exists.
- "index" now has the default of "logstash-%{+YYYY.MM.dd}".
## config.yml

Set default template version to use to "2.1.1-1-rancher1"
# Changes from Kibana v4.1.1 template
## docker-compose.yml

Use kibana:4.3.1 image from docker hub.
## rancher-compose.yml

Set template version to "4.3.1-rancher1"
## config.yml

Set default template version to use to "4.3.1-rancher1"

### CODE REVIEW

**Comment by mgolly** [comment]
Please only merge this once merge request 41 in compose-templates has merged and the new docker images are built.

**Comment by mgolly** [comment]
Grrr, wrong button.

**Comment by mgolly** [comment]
Note - kibana v4.1.1 cannot be used with elasticsearch v2 or later.  That is why I added kibana to this pull request.

**Comment by cloudnautique** [comment]
Cool! Thanks for updating here and the compose-templates. 

Are there any considerations in upgrading from the previous template to this version? Once, a new version goes out, all deployed entries will show the "upgrade available" button. I saw there were some patterns a while ago that some things in 1.7.x will not work in 2.0.

**Comment by mgolly** [comment]
The considerations for upgrading stem from the changes in data layout in elasticsearch.  The elasticsearch people recommend a full cluster reboot and not a rolling upgrade when going from 1.x to 2.x.

Here are some links that describe the situation for upgrading:
https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes.html
https://www.elastic.co/blog/key-point-to-be-aware-of-when-upgrading-from-elasticsearch-1-to-2
https://www.elastic.co/webinars/upgrading-from-elasticsearch-1-x-to-2-x

And finally there is an elasticsearch plugin for testing if a particular elasticsearch instantiation is ready for upgrade to 2.x:
https://github.com/elastic/elasticsearch-migration

As for patterns that won't work any more, I would guess that they would be called out in the second link above (i.e. "key-points-to-be-aware-of").  I wasn't impacted by any of that probably because I am using the full ELK stack and have no customized software directly interacting with elasticsearch.  (BTW, I am also using the latest Grafana 2.6.0, and IMHO it is much better than Kibana, but Grafana does have a greater learning curve - look for a Grafana catalog soon).

My chosen path was to bring up a completely new cluster and "blow away" my old one, but I was in a development environment and my data wasn't critical.

However, I did do simple tests on just upgrading the docker images from the **infrastructure** container list (and not through a template).  The upgrade didn't work due to the behavioral changes in (1) _config/scripts_ directory being **required** now and it not being created automatically, and (2) the default bind address (from all addresses "0.0.0.0" in 1.x to just localhost "127.0.0.1" in 2.x).  That's how I found out that Rancher's _elasticsearch-conf_ now must create the _config/scripts_ directory as well as specifically state in the config which address to bind to.  I didn't go any further down this testing path once I figured out what a new _elasticsearch-conf_ image (and "kopf", too) had to do to work.

So, should I/we create an "elasticsearch 2.x" catalog entry to sit next to the "elasticsearch" entry?  This would force a second logstash and kibana entry as well, so the tradeoffs should be considered....

**Comment by mgolly** [comment]
Just wondering if you are going to accept this pull or should I set the pull up to go to the community repo?

**Comment by mgolly** [comment]
@cloudnautique - just wondering if you are going to pull this in or should I rebase this pull request to go to the community repo?

**Comment by cloudnautique** [comment]
I would like to merge here, but I have not had the time to test this out. I do think making it a separate Elasticsearch 2.0 template since upgrading is not necessarily straight forward. I probably won't be able to get to this until maybe next week sometime. 

If you want to create templates under mgolly and open a PR in community under Elasticsearch 2.0, we could get it in this week. Then when there is more time pull it in to the Rancher catalog.

**Comment by dominikhahn** [comment]
@cloudnautique @mgolly updated to newer versions:
https://github.com/rancher/rancher-catalog/pull/110

**Comment by andyshinn** [comment]
Any movement on ES 2.0? Looking to move one of my single ES nodes over to Rancher to try out the clustering. But I need the data format in 2.0+. Let me know if cycles are thin and I'll try to spin out a PR for an elasticsearch2 template separated from the current 1.7.x.

**Comment by cloudnautique** [comment]
We have moved our ES template over to Community catalog.

@andyshinn, I think the ES 2.0 entry would be awesome. It seems theres a lot of interest, and we have been slammed getting ready for GA. If you would take a stab at it we would appreciate it.
/cc @mgolly @dominikhahn .

**Pull request closed without merging**
